### PR TITLE
Refactor react component patterns

### PR DESCRIPTION
**Pull request by john-d-pelingo**
Refactor react component patterns (#71)

Fixed a couple of dead links on the road.

### CODE REVIEW

**Comment by markerikson** [comment]
Looks pretty good!  The only issue I see is that the Michael Jackson link needs two spaces added at the end of the title and link lines, so that the formatting is correct (the spaces force a newline).

**Comment by john-d-pelingo** [comment]
I've been searching how to force these newlines at both text and visual representations of markdowns for a long time now. Today I learned. 💯

**Comment by markerikson** [comment]
Yeah, I had to do some experimenting and research myself to figure that out in the first place.  (And of course, most people including myself don't have "Show Whitespace" turned on in an editor, and editors sometimes strip extra whitespace.  So, several times outside contributions have borked the formatting of new or existing entries.)

So, I think this only needs one more thing.  Since we've moved the sub-categories into a new page, any external links to `react-component-patterns.md#higher-order-components` will fail to match, and just leave the page as it is.  I'd like to add a couple invisible anchor tags right above the "React Component Composition" link you put in there, like:

```
<a href="#higher-order-components"></a>
<a href="#functional-composition"></a>
- [React Component Composition](./react-component-composition.md)
```

That way, I think that hitting the page with that hash anchor should jump it down a bit to bring the link to the top.

**Comment by john-d-pelingo** [comment]
Just tried the above hack in a dummy repo. Doesn't seem to scroll me to `#higher-order-components` or `#function-composition` when added at the end of the url.

**Comment by markerikson** [comment]
Awright, cool.  I might tweak a couple things later, but this is probably sufficient for now.  HIT THE BIG GREEN BUTTON!

**Pull request merged**
