### PR TITLE
Add react-boilerplate

### PR DESCRIPTION
**Pull request by mxstbr**
Add react-boilerplate to boilerplates-and-starter-kits.md

### CODE REVIEW

**Comment by markerikson** [comment]
Whoa, whoa, hey now.  You can't just go submitting your own project to a list of links like this!  That'd be like submitting something you wrote to Reddit or HN.  Blatant self-promotion!

:)

Seriously, that's a pretty solid project there, and thanks for reminding me it exists.

**Comment by mxstbr** [comment]
Well, if Shakespeare submitted his works to a book club... :wink:

Just kidding, it was more of a suggestion - glad you think it's useful to have!

**Comment by markerikson** [comment]
/me carefully does not look in the direction of the other link he added to the boilerplates page just a bit earlier...

**Comment by mxstbr** [comment]
:joy:

**Pull request merged**
