### PR TITLE
Adding Understand and implement your own Redux

### PR DESCRIPTION
**Pull request by jakelumetta**
I didn't make the link text bold because none of the other links are bold. If you'd like me to update that just let me know.  Thanks!

### CODE REVIEW

**Comment by jakelumetta** [comment]
Hi - just wanted to follow up on this.

**Comment by markerikson** [comment]
Appreciate the PR, but I don't feel that article is something that's worth adding to the list at this point.

**Comment by jakelumetta** [comment]
Thanks @markerikson - any guidance on what's a better for future reference?

**Comment by jakelumetta** [comment]
Hi Mark - just wanted to follow up. Any guidance for the future?

**Pull request closed without merging**
